// paint-emit.mjs — emits a standalone HyperFrames composition from compiled
// strokes: index.html (contract-correct root + clip + timeline), strokes.js
// (editable data module), painter.js (seek-safe banded reveal runtime).

/**
 * @typedef {import("./paint-compiler.mjs").Stroke} Stroke
 */

/**
 * @typedef {Object} EmitOptions
 * @property {string} id  composition id (kebab-case)
 * @property {Stroke[]} strokes
 * @property {number} width
 * @property {number} height
 * @property {number} duration  seconds
 * @property {[number, number, number]} background
 */

/**
 * Emit the composition files. Returns a map of relative path -> file content.
 * @param {EmitOptions} opts
 * @returns {Record<string, string>}
 */
export function emitComposition(opts) {
  const { id, strokes, width, height, duration, background } = opts;
  const bands = Math.max(8, Math.min(32, Math.ceil(strokes.length / 1200)));
  const config = {
    id,
    width,
    height,
    duration,
    bands,
    background: `rgb(${background[0]},${background[1]},${background[2]})`,
  };
  // The painter runtime is inlined into index.html so static analysis (and
  // `hyperframes lint`) sees the timeline registration; strokes.js stays an
  // external, editable data module.
  return {
    "index.html": indexHtml(config) + "<script>\n" + painterSource(config) + "</script>\n",
    "strokes.js": strokesModule(strokes),
  };
}

/** @param {Stroke[]} strokes */
function strokesModule(strokes) {
  const rows = strokes
    .map(
      (s) =>
        `{"x":${s.x},"y":${s.y},"len":${s.len},"angle":${s.angle},"bend":${s.bend},"color":[${s.color[0]},${s.color[1]},${s.color[2]}],"weight":${s.weight},"alpha":${s.alpha}}`,
    )
    .join(",\n");
  // Editable data module: reorder, retune, or delete strokes — the painter
  // reveals them in array order.
  return `window.__PAINT_STROKES = [\n${rows}\n];\n`;
}

/**
 * @typedef {{ id: string, width: number, height: number, duration: number, bands: number, background: string }} PainterConfig
 * @param {PainterConfig} cfg
 */
function indexHtml(cfg) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=${cfg.width}, height=${cfg.height}" />
    <title>paint — ${cfg.id}</title>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { width: ${cfg.width}px; height: ${cfg.height}px; overflow: hidden; background: #000; }
      #root { position: relative; width: ${cfg.width}px; height: ${cfg.height}px; overflow: hidden; background: #000; }
      .clip { position: absolute; inset: 0; }
      canvas { display: block; width: 100%; height: 100%; }
    </style>
  </head>
  <body>
    <div
      id="root"
      data-composition-id="${cfg.id}"
      data-start="0"
      data-width="${cfg.width}"
      data-height="${cfg.height}"
      data-duration="${cfg.duration}"
    >
      <section id="paint-clip" class="clip" data-start="0" data-duration="${cfg.duration}" data-track-index="1">
        <canvas id="paint-canvas" width="${cfg.width}" height="${cfg.height}"></canvas>
      </section>
    </div>
    <script src="strokes.js"></script>
  </body>
</html>
`;
}

/**
 * The emitted runtime. Seek-safe by construction: band canvases are pure
 * functions of their band index (drawn once, cached), and the partial band is
 * redrawn from scratch on every update, so any seek order lands on identical
 * pixels. Per-frame cost is O(strokes/bands) plus bandCount drawImage calls.
 * @param {PainterConfig} cfg
 */
export function painterSource(cfg) {
  return `// painter.js — generated by hyperframes media-use paint.
// Reveals the stroke data in array order over ${cfg.duration}s. Seek-safe:
// canvas state is a pure function of timeline progress. Edit strokes.js to
// reshape the painting; this file never needs to change.
(function () {
  "use strict";
  var strokes = window.__PAINT_STROKES || [];
  var W = ${cfg.width};
  var H = ${cfg.height};
  var DURATION = ${cfg.duration};
  var BANDS = ${cfg.bands};
  var BG = ${JSON.stringify(cfg.background)};


  var canvas = document.getElementById("paint-canvas");
  var ctx = canvas.getContext("2d");
  var per = Math.ceil(strokes.length / BANDS) || 1;
  var bandCount = Math.max(1, Math.ceil(strokes.length / per));

  function drawStroke(g, s) {
    g.strokeStyle = "rgb(" + s.color[0] + "," + s.color[1] + "," + s.color[2] + ")";
    g.lineWidth = s.weight;
    g.globalAlpha = s.alpha;
    var rad = (s.angle * Math.PI) / 180;
    var dx = Math.cos(rad), dy = -Math.sin(rad);
    var half = s.len / 2;
    g.beginPath();
    g.moveTo(s.x - dx * half, s.y - dy * half);
    g.quadraticCurveTo(s.x - dy * s.bend, s.y + dx * s.bend, s.x + dx * half, s.y + dy * half);
    g.stroke();
  }

  // band canvases: transparent, strokes only; drawn once per band index
  var bands = [];
  for (var b = 0; b < bandCount; b++) {
    var bc = document.createElement("canvas");
    bc.width = W;
    bc.height = H;
    var bctx = bc.getContext("2d");
    bctx.lineCap = "round";
    bctx.lineJoin = "round";
    var start = b * per;
    var end = Math.min(strokes.length, start + per);
    for (var i = start; i < end; i++) drawStroke(bctx, strokes[i]);
    bands.push(bc);
  }

  var scratch = document.createElement("canvas");
  scratch.width = W;
  scratch.height = H;
  var sctx = scratch.getContext("2d");
  sctx.lineCap = "round";
  sctx.lineJoin = "round";

  function paintAt(progress) {
    var drawn = progress * strokes.length;
    var full = Math.min(bandCount, Math.floor(drawn / per));
    ctx.globalAlpha = 1;
    ctx.fillStyle = BG;
    ctx.fillRect(0, 0, W, H);
    for (var b = 0; b < full; b++) ctx.drawImage(bands[b], 0, 0);
    var cur = full;
    if (cur < bandCount && drawn > cur * per) {
      sctx.clearRect(0, 0, W, H);
      var end = Math.min(strokes.length, Math.ceil(drawn));
      for (var i = cur * per; i < end; i++) drawStroke(sctx, strokes[i]);
      ctx.drawImage(scratch, 0, 0);
    }
  }

  window.__timelines = window.__timelines || {};
  var tl = gsap.timeline({ paused: true });
  var proxy = { p: 0 };
  tl.to(proxy, { p: 1, duration: DURATION, ease: "none", onUpdate: function () { paintAt(proxy.p); } }, 0);
  window.__timelines[${JSON.stringify(cfg.id)}] = tl;
  paintAt(0);
})();
`;
}
