/**
 * Fails when the committed catalog vector artifact no longer covers the
 * registry it is meant to search.
 *
 * The artifact is regenerated by hand: nothing in CI or in a hook rebuilds it,
 * because embedding needs the 32 MB model. So adding a registry item silently
 * makes it invisible to meaning search until someone remembers. Removing one is
 * self-healing (the ranker filters names it cannot install), which is why the
 * asymmetry is easy to miss.
 *
 * Comparing the two name lists needs no model and no network, so it is cheap
 * enough to run on every change that touches either side.
 */
import { readFileSync } from "node:fs";

type RegistryItem = { name: string; type?: string };
type Registry = { items: RegistryItem[] };
type Artifact = { model?: string; dimensions?: number; names?: string[] };

const REGISTRY = "registry/registry.json";
const ARTIFACT = "registry/catalog-artifact/local-vectors.json";

function read<T>(path: string): T {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch (error) {
    console.error(`Could not read ${path}: ${(error as Error).message}`);
    process.exit(1);
  }
}

const registry = read<Registry>(REGISTRY);
const artifact = read<Artifact>(ARTIFACT);

// Only blocks and components are searchable moves. Examples are starter
// projects a user scaffolds, never something `catalog` ranks, so the artifact
// deliberately carries no vector for them and demanding one would keep this
// gate permanently red.
const SEARCHABLE = new Set(["hyperframes:block", "hyperframes:component"]);
const registryNames = new Set(
  registry.items.filter((i) => SEARCHABLE.has(i.type ?? "")).map((i) => i.name),
);
const artifactNames = new Set(artifact.names ?? []);

const unindexed = [...registryNames].filter((n) => !artifactNames.has(n)).sort();
const dropped = [...artifactNames].filter((n) => !registryNames.has(n)).sort();

const show = (names: string[]) =>
  names
    .slice(0, 10)
    .map((n) => `    ${n}`)
    .join("\n") + (names.length > 10 ? `\n    ... and ${names.length - 10} more` : "");

console.log(`registry: ${registryNames.size} searchable items (blocks + components)`);
console.log(`artifact: ${artifactNames.size} vectors (${artifact.model ?? "unknown model"})`);

if (dropped.length > 0) {
  // Not fatal: the CLI filters these before a user ever sees them.
  console.log(`\nnote: ${dropped.length} vector(s) name items the registry no longer has.`);
  console.log(show(dropped));
  console.log("  These are filtered at search time, so they cost space, not correctness.");
}

if (unindexed.length === 0) {
  console.log("\nEvery registry item has a vector. Meaning search can see the whole catalog.");
  process.exit(0);
}

console.error(`\n${unindexed.length} registry item(s) have no vector:`);
console.error(show(unindexed));
console.error(
  "\nMeaning search cannot return these at all: they are absent from the candidate\n" +
    "set, not ranked low. Word search still finds them.\n\n" +
    "Regenerate and commit the artifact:\n" +
    "  bun scripts/catalog/build-local-vectors.ts\n",
);
process.exit(1);
